
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_service?createDatabaseIfNotExist=true&useSSL=false
    username: dev
    password: 4567
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
