spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reserveInfoDb?createDatabaseIfNotExist=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  server:
    port: 8082
