#server:
#  port: 8191

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/sample
    url: jdbc:mysql://localhost:3306/sample2?createDatabaseIfNotExist=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create